# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-04 03:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('task', '0005_remove_group_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='group',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='user',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='task',
            name='group',
            field=models.CharField(max_length=50, verbose_name='Grupo da Tarefa'),
        ),
    ]
