# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-04 04:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0006_auto_20170204_0055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='group',
        ),
        migrations.RemoveField(
            model_name='task',
            name='user',
        ),
        migrations.AddField(
            model_name='task',
            name='id_group',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='task.Group'),
        ),
    ]
